services:
  nats:
    build:
      context: ./nats
    container_name: nats
    ports:
      - "4222:4222"
    networks:
      - app-network
  api:
    build:
      context: ./api
    container_name: api
    environment:
      - NATS_SERVER=nats://nats:4222
      - SUBJECT=subject
      - JWT_KEY=jwt-key
      - JWT_SECRET=jwt-secret
    ports:
      - "3000:3000"
    depends_on:
      - nats
    networks:
      - app-network
  proxy:
    build:
      context: ./proxy
    container_name: proxy
    ports:
      - "9080:9080"
    depends_on:
      - api
    networks:
      - app-network
  worker:
    build:
      context: ./worker
    container_name: worker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - NATS_SERVER=nats://nats:4222
      - SUBJECT=subject
    depends_on:
      - nats
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
